/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/Home/about.vue')['default']
    BubbleChart: typeof import('./components/dataViz/hw6/BubbleChart.vue')['default']
    Contact: typeof import('./components/contact.vue')['default']
    DataViz: typeof import('./components/dataViz/dataViz.vue')['default']
    Games: typeof import('./components/Games/games.vue')['default']
    GapPlot: typeof import('./components/dataViz/hw4/components/gapPlot.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home/home.vue')['default']
    Hw4: typeof import('./components/dataViz/hw4/hw4.vue')['default']
    Hw5: typeof import('./components/dataViz/hw5/hw5.vue')['default']
    Hw6: typeof import('./components/dataViz/hw6/hw6.vue')['default']
    InfoBox: typeof import('./components/dataViz/hw4/components/infoBox.vue')['default']
    Map: typeof import('./components/dataViz/hw4/components/map.vue')['default']
    Minesweeper: typeof import('./components/Games/minesweeper.vue')['default']
    ProjectDetail: typeof import('./components/SideProjects/ProjectDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideProjects: typeof import('./components/SideProjects/SideProjects.vue')['default']
    Table: typeof import('./components/dataViz/hw5/table.vue')['default']
    Tetris: typeof import('./components/Games/tetris.vue')['default']
    Tree: typeof import('./components/dataViz/hw5/tree.vue')['default']
  }
}
