/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/Home/about.vue')['default']
    Contact: typeof import('./components/Contact.vue')['default']
    Home: typeof import('./components/Home/home.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    ProjectDetail: typeof import('./components/SideProjects/ProjectDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideProjects: typeof import('./components/SideProjects/SideProjects.vue')['default']
    Tetris: typeof import('./components/Games/tetris.vue')['default']
  }
}
